[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/0_Keywords-Research-beta.py"
name = "Keywords-research"
icon = "ğŸ’»"

[[pages]]
path = "pages/1_Robby-Chat-file.py"
name = "Robby-Chat-file"
icon = "ğŸ“„"

[[pages]]
path = "pages/2_Robby-Chat-web.py"
name = "Robby-Chat-web"
icon = "ğŸŒ"

[[pages]]
path = "pages/3_Text-Similarity-beta.py"
name = "Text-Similarity-score"
icon = "ğŸ“š"

[[pages]]
path = "pages/download.py"
name = "download"