[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_Robby-Chat-file.py"
name = "Robby-Chat-file"
icon = "ğŸ“„"

[[pages]]
path = "pages/2_Robby-Chat-web.py"
name = "Robby-Chat-web"
icon = "ğŸŒ"

[[pages]]
path = "pages/download.py"
name = "download"